# --- Paths ---
# Directory containing the original SA-1B image folders (e.g., sa_000000, sa_000001)
sa1b_base_dir: /media/dataset2/hyunbin/SA-1B/
# Specific SA-1B sub-folder to process (e.g., sa_000000) - Used to build full input path
sa1b_subfolder: sa_000000

# Path to the root of the Bridge Text Spotting repository
bridge_repo_dir: /home/cvlab12/project/hyunbin/text_restoration/Bridging-Text-Spotting
# Path to the Bridge config file within the repo
bridge_config_file: configs/Bridge/TotalText/R_50_poly.yaml
# Path to the Bridge model weights file
bridge_weights_file: Bridge_tt.pth # Assumes it's in the bridge_repo_dir

# --- Output Paths ---
# Base directory where intermediate files and cropped images will be saved
intermediate_output_base_dir: /media/dataset2/hyunbin/generated_data/SA-1B/ # <--- CHANGE THIS
# Directory where the final dataset.json will be saved
final_dataset_dir: /media/dataset2/hyunbin/generated_data/SA-1B/ # <--- CHANGE THIS

# --- Logging ---
log_filename: "pipeline.log"          # Base name for the log file within intermediate_output_base_dir+suffix
log_level_console: "INFO"             # Level for terminal (DEBUG, INFO, WARNING, ERROR)
log_level_file: "DEBUG"               # Level for file (DEBUG, INFO, WARNING, ERROR)

# --- Model & Environment Settings ---
# Command prefix to activate Bridge environment and run python
# Example: "conda run -n Bridge python" or "/path/to/bridge_env/bin/python"
# If empty, it assumes 'python' is correct in the activated Bridge env (requires manual activation before running main_pipeline.py)
bridge_env_python: "conda run -n Bridge python"

# Names for VLM models used in filenames and potentially internal logic
vlm1_name: "OVIS"
vlm2_name: "Qwen"
blur_vlm_name: "Qwen" # VLM used for blur assessment

# --- Parameters ---
crop_size: 512
bridge_confidence_threshold: 0.3
max_crops_per_image: 3 # From data_gen_polygons.py default

# --- Blur Assessment ---
# Use inverse prompt (sharpness levels) for blur assessment? (Matches Thirteenth Prompt)
blur_inverse_prompt: True
# Category name in the blur CSV that signifies a non-blurry image
blur_keep_category: "Not blurry" # This is the mapped output category, even if using inverse prompt

# --- Optional ---
# Set to true to keep intermediate JSON/CSV files (useful for debugging)
keep_intermediate_files: True